Code/PresPrice/config/routes.rb
# Name: Gabby Johnson
# Course: CSC 415
# Semester: Fall 2017
# Instructor: Dr. Pulimood 
# Project name: PresPrice
# Description: The app is intended to provide the cheapest price of a medicine to users
# Filename: routes.rb
# Description: To connect addresses to functions in controllers that will display their respective views
# Last modified on: 11/30/17

Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

 
   get 'signup'  => 'users#new'
   get '/login'  => 'sessions#new'
   post 'login' => 'sessions#create'
   delete 'logout' => 'sessions#destroy' 

   root 'search#index'
   get 'users' => 'users#new'
   
   get 'searchbar' => 'search#index'  
   get 'searchbar2' => 'search#index2'
   
   get 'results' => 'search#results', as: :search
   get 'results2' => 'search#results2', as: :search2
   resources :users, :medicines, :searches

end

Code/PresPrice/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

Code/PresPrice/app/models/medicine.rb
# Name: Gabby Johnson
# Course: CSC 415
# Semester: Fall 2017
# Instructor: Dr. Pulimood 
# Project name: PresPrice
# Description: The app is intended to provide the cheapest price of a medicine to users
# Filename: medicine.rb
# Description: Take parameter to search and order medicines
# Last modified on: 11/30/17
class Medicine < ApplicationRecord
   def self.search(search)
    if search
      where("name LIKE ? ", "%#{search}%")
    else
      order('name DESC')
    end
  end
end

Code/PresPrice/app/models/search.rb
class Search < ApplicationRecord
		belongs_to :medicine

	def medicine_name
	  medicine.try(:name)
	end

	def medicine_name=(name)
	  self.medicine = Medicine.find_by(name: name) if name.present?
	end

	def medicine_name=(name)
	  self.medicine = Medicine.find_or_create_by(name: name) if name.present?
	end
end

Code/PresPrice/app/models/user.rb
# Name: Gabby Johnson
# Course: CSC 415
# Semester: Fall 2017
# Instructor: Dr. Pulimood 
# Project name: PresPrice
# Description: The app is intended to provide the cheapest price of a medicine to users
# Filename: user.rb
# Description: Sets validatation for sign up parameters
# Last modified on: 11/30/17
class User < ApplicationRecord
	#ActiveRecord::Base

	has_secure_password

    validates :password, presence: true, length: { minimum: 6 }, confirmation: true
    VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
    validates :email, presence: true, length: { maximum: 255 },
                     format: { with: VALID_EMAIL_REGEX },
                     uniqueness: { case_sensitive: false }
    validates :first_name, presence:true
    validates :last_name, presence:true
	
end

Code/PresPrice/app/controllers/application_controller.rb
# Name: Gabby Johnson
# Course: CSC 415
# Semester: Fall 2017
# Instructor: Dr. Pulimood 
# Project name: PresPrice
# Description: The app is intended to provide the cheapest price of a medicine to users
# Filename: application_controller.rb
# Description: Respond to model
# Last modified on: 11/30/17

class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  include SearchHelper, SessionsHelper, ApplicationHelper
  helper_method :SessionsHelper

	 def respond_modal_with(*args, &blk)
	    options = args.extract_options!
	    options[:responder] = ModalResponder
	    respond_with *args, options, &blk
	  end
end

Code/PresPrice/app/controllers/medicines_controller.rb
class MedicinesController < ApplicationController
	  def index
	    @medicines = Medicine.order(:name).where("name like ?", "%#{params[:term]}%")
	    render json: @searches.map(&:name)
	  end
end

Code/PresPrice/app/controllers/search_controller.rb
# Name: Gabby Johnson
# Course: CSC 415
# Semester: Fall 2017
# Instructor: Dr. Pulimood 
# Project name: PresPrice
# Description: The app is intended to provide the cheapest price of a medicine to users
# Filename: search_controller.rb
# Description: Defined methods that access views
# Last modified on: 11/30/17

class SearchController < ApplicationController
	before_action :require_user, only: [:index, :show]
	include SearchHelper

	#Search bar for one medicine
	def index
 		@medicines = Medicine.all
	end

	#Search bar for two medicines
	def index2

	end

	def results
	  #Results for one medicine search
	  @medicines = Medicine.all
	    if params[:search]
	    	#orders found medicine
	      @medicines = Medicine.search(params[:search]).order("created_at DESC")
	    end
	end

	
	def results2
		#Results for two medicine searches
		#creates separate medicines instances so they're printed separately
	  @medicines1 = Medicine.all
	    if params[:search1]
	      @medicines1 = Medicine.search(params[:search1]).order("created_at DESC")
	    end

      @medicines2 = Medicine.all
	    if params[:search2]
	      @medicines2 = Medicine.search(params[:search2]).order("created_at DESC")
	    end

	end

	def new
		@search = Search.new
	end


  private
  def allowed_params
    params.require(:search).permit!
  end

end

Code/PresPrice/app/controllers/sessions_controller.rb
# Name: Gabby Johnson
# Course: CSC 415
# Semester: Fall 2017
# Instructor: Dr. Pulimood 
# Project name: PresPrice
# Description: The app is intended to provide the cheapest price of a medicine to users
# Filename: sessions_controller.rb
# Description: Validates if user is logged in or not.  If they are they are redirected to the main search page.
# Last modified on: 11/30/17
class SessionsController < ApplicationController
	def new 
	end

	def create
  		@user = User.find_by_email(params[:session][:email])
  	 
  	 if params[:session][:email].blank? || params[:session][:password].blank?
              redirect_to '/searchbar'
              return
     end 

	  if @user && @user.authenticate(params[:session][:password])
	    session[:user_id] = @user.id
	    redirect_to '/searchbar'
	  else
	    redirect_to '/login'
		  end 
	end

	def destroy 
	  session[:user_id] = nil 
	  redirect_to '/' 
	end
		
end

Code/PresPrice/app/controllers/users_controller.rb
# Name: Gabby Johnson
# Course: CSC 415
# Semester: Fall 2017
# Instructor: Dr. Pulimood 
# Project name: PresPrice
# Description: The app is intended to provide the cheapest price of a medicine to users
# Filename: index.html.erb
# Description: To create user account
# Last modified on: 11/30/17 
class UsersController < ApplicationController
	 helper_method :match_password

	def new
  		@user = User.new
	end

	def create 
	  @user = User.new(user_params) 
	  if @user.save 
	    #If user is validated user will be redirected to searchbar
	    session[:user_id] = @user.id 
	    redirect_to '/searchbar' 
	  else 
	    render :new
	    #redirected to signup '/signup' 
	  end 
	end

	private
  def user_params
  	#parameters for signup
    params.require(:user).permit(:first_name, :last_name, :email, :password, :password_confirmation)
  end
end

Code/PresPrice/app/helpers/application_helper.rb
# Name: Gabby Johnson
# Course: CSC 415
# Semester: Fall 2017
# Instructor: Dr. Pulimood 
# Project name: PresPrice
# Description: The app is intended to provide the cheapest price of a medicine to users
# Filename: application_helper.rb
# Description: Defines flash characteristics
# Last modified on: 11/30/17
module ApplicationHelper
	def flash_class(level)
    return case level
      when 'notice' then "alert alert-info"
      when 'success' then "alert alert-success"
      when 'error' then "alert alert-danger"
      when 'alert' then "alert alert-warning"
    end
  end
end

Code/PresPrice/app/helpers/medicines_helper.rb
module MedicinesHelper
end

Code/PresPrice/app/helpers/pages_helper.rb
module PagesHelper
end

Code/PresPrice/app/helpers/search_helper.rb
module SearchHelper
  
end

Code/PresPrice/app/helpers/sessions_helper.rb
module SessionsHelper
  def current_user 
    @current_user ||= User.find(session[:user_id]) if session[:user_id] 
    rescue ActiveRecord::RecordNotFound
  end
  
  def require_user 
    redirect_to '/login' unless current_user 
  end
end

Code/PresPrice/app/helpers/users_helper.rb
module UsersHelper
end

Code/PresPrice/app/views/layouts/application.html.erb
<!--# Name: Gabby Johnson
# Course: CSC 415
# Semester: Fall 2017
# Instructor: Dr. Pulimood 
# Project name: PresPrice
# Description: The app is intended to provide the cheapest price of a medicine to users
# Filename: application.html.erb
# Description: Displays navigation links at the top of pages
# Last modified on: 11/30/17-->
<!DOCTYPE html>

<html>
  <head>
    <link href="http://s3.amazonaws.com/codecademy-content/projects/bootstrap.min.css" rel="stylesheet" />
    <link href='http://fonts.googleapis.com/css?family=Roboto:400,500,300' rel='stylesheet' type='text/css'>
    <%= csrf_meta_tags %>
    <%= action_cable_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <body>

    <div class="header">
      <div class="container">
     

        <div class="nav pull-right">
          <% if current_user %> 
              <ul> 
                  <a href="searchbar">Search</a>
                <li><%= current_user.email %></li> 
                <li><%= link_to "Log out", logout_path, method: "delete" %></li> 
              </ul> 
          <% else %> 
            <ul> 
              <a href = "login">Log In</a>
              <a href = "signup">Sign Up</a>
            </ul> 
          <% end %>
          
        </div>
      </div>
    </div>
  

  <!--maybe change this -->
    
      <%= yield %>
    </div>

  </body>
</html>

Code/PresPrice/app/views/search/_form.html.erb
<%= form_for (@search) do |f| %>
  <div class="field">
    <%= f.label :generic %><br />
    <%= f.text_field :generic%>
  </div>

  <div class="field">
    <%= f.label :walmart_price %><br />
    <%= f.text_field :walmart_price %>
  </div>

  <div class="field">
    <%= f.label :medicine %><br />
    <%= f.text_field :medicine, data: {autocomplete_source: medicines_path} %><br />

  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

Code/PresPrice/app/views/search/index.html.erb
<!-- Name: Gabby Johnson
# Course: CSC 415
# Semester: Fall 2017
# Instructor: Dr. Pulimood 
# Project name: PresPrice
# Description: The app is intended to provide the cheapest price of a medicine to users
# Filename: index.html.erb
# Description: To allow user to search for medicine through a form
# Last modified on: 11/30/17 -->

<%= stylesheet_link_tag 'https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css' %>
<%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
<%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

<div class = "header">
</div>

<div class="main">
  <div class="login">
    <div class="container">

      <div id = "home">
  <h1>PresPrice</h1>
    <div class="form">
           <!--Gives form path that form will be passing to-->
           <%= form_tag(search_path, :method => "get", id: "search-form") do %>
           <!--Search parameter-->
            <%= text_field_tag :search, params[:search], placeholder: "Search medicines" %><br>
            <%= submit_tag "Search", class: "buttoncolor", :name => nil %>
           <% end %>
           <li><a href = "searchbar2">Search Two Medications</a></li>
        </div>
  
    
    </div>
  </div>
</div>
     
     <!--Multiple Medicines-->
  

<footer class="footer">
      <div class="container">
        <p>Copyright 2017</p>
      </div>
</footer>

Code/PresPrice/app/views/search/index2.html.erb
<!--
# Name: Gabby Johnson
# Course: CSC 415
# Semester: Fall 2017
# Instructor: Dr. Pulimood 
# Project name: PresPrice
# Description: The app is intended to provide the cheapest price of a medicine to users
# Filename: index2.html.erb
# Description: Take two parameters to search for separate medicines
# Last modified on: 11/30/17-->

<%= stylesheet_link_tag 'https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css' %>
<%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
<%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

<div class = "header">
</div>

<div class="main">
  <div class="login">
    <div class="container">
      <div id = "home">
		  <h1>PresPrice</h1>
		    <div class="form">
		           <%= form_tag(search2_path, :method => "get", id: "search-form") do %>
		            <%= text_field_tag :search1, params[:search1], placeholder: "Search medicine 1" %><br>
		            <%= text_field_tag :search2, params[:search2], placeholder: "Search medicine 2" %><br>
		            <%= submit_tag "Search", class: "buttoncolor", :name => nil %>
		           <% end %>
		           <li><a href = "searchbar">Search 1 Medication</a></li>
        	</div>   
	    </div>
	  </div>
	</div>
        

<footer class="footer">
      <div class="container">
        <p>Copyright 2017</p>
      </div>
</footer>

Code/PresPrice/app/views/search/new.html.erb
<h1>New Medicine</h1>

<%= render 'form' %>

Code/PresPrice/app/views/search/results.html.erb
  <!--# Name: Gabby Johnson
# Course: CSC 415
# Semester: Fall 2017
# Instructor: Dr. Pulimood 
# Project name: PresPrice
# Description: The app is intended to provide the cheapest price of a medicine to users
# Filename: results.html.erb
# Description: Display results for ome parameter search term and all medicines found
# Last modified on: 11/30/17-->
  <% if @medicines.blank? %>
  	<h4> There are no scholarships that match your query </h4>
  <% else %>
    <table class="table table-striped">
          <tr>
          <!--Column Headings-->
              <th>Name</th>
              <th>Walmart Price</th>
              <th>CVS Price</th>
              <th>Walgreens Price</th>
              <th>RiteAid Price</th>
              <th>Generic</th>
          </tr>
          <% @medicines.each do |medicine| %>
            <tr>     
        </td>
        <!--Found Medicine values-->
          	  <td><%= medicine.name %></td>
              <td><%= medicine.walmart_price  %></td>
          	  <td><%= medicine.cvs_price  %></td>
          	  <td><%= medicine.walgreens_price  %></td>
          	  <td><%= medicine.riteaid_price %></td>
              <td><%= medicine.generic %></td>
            </tr>
      <% end %>
    </table> 
<% end %>

Code/PresPrice/app/views/search/results2.html.erb
<!--
# Name: Gabby Johnson
# Course: CSC 415
# Semester: Fall 2017
# Instructor: Dr. Pulimood 
# Project name: PresPrice
# Description: The app is intended to provide the cheapest price of a medicine to users
# Filename: results2.html.erb
# Description: Display column headings and iterate through Medicine Items Found through search
# Last modified on: 11/30/17-->
  <% if @medicines1.blank? %>
      <h4> There are no scholarships that match your query </h4>
  <% else %>
    <h4>Medicine 1 Results</h4> 
        <table class="table table-striped">
          <tr>
            <th>Name</th>
            <th>Walmart Price</th>
            <th>CVS Price</th>
            <th>Walgreens Price</th>
            <th>RiteAid Price</th>
            <th>Generic</th>
          
          </tr>

        <% @medicines1.each do |medicine| %>
          <tr>   
        </td>
            <td><%= medicine.name %></td>
            <td><%= medicine.walmart_price  %></td>
            <td><%= medicine.cvs_price  %></td>
            <td><%= medicine.walgreens_price  %></td>
            <td><%= medicine.riteaid_price %></td>
              <td><%= medicine.generic %></td>
          </tr>
      <% end %>
    </table> 


  <h4>Medicine 2 Results</h4>

  <% if @medicines2.blank? %>
      <h4> There are no scholarships that match your query </h4>
  <% else %>
        <table class="table table-striped">
          <tr>
            <th>Name</th>
            <th>Walmart Price</th>
            <th>CVS Price</th>
            <th>Walgreens Price</th>
            <th>RiteAid Price</th>
            <th>Generic</th>
          </tr>
        <% @medicines2.each do |medicine| %>
        <tr>    
          </td>
              <td><%= medicine.name %></td>
              <td><%= medicine.walmart_price  %></td>
              <td><%= medicine.cvs_price  %></td>
              <td><%= medicine.walgreens_price  %></td>
              <td><%= medicine.riteaid_price %></td>
                <td><%= medicine.generic %></td>
                </tr>
              <% end %>

      </table> 
  <% end %>
<% end %>


   
  
           

Code/PresPrice/app/views/users/new.html.erb
<!--
# Name: Gabby Johnson
# Course: CSC 415
# Semester: Fall 2017
# Instructor: Dr. Pulimood 
# Project name: PresPrice
# Description: The app is intended to provide the cheapest price of a medicine to users
# Filename: new.html.erb
# Description: To provide a form for the user to signup for the PresPrice application, also validates input
# Last modified on: 11/30/17
-->
<%= form_for @user, :html=> {:class => "form"} do |f| %>
<!--Prints out errors for form input -->
<% if @user.errors.any? %>
<!--Iterates through error messages-->

     <div id="container">
        <% flash.each do |key, value| %>
           <div class="<%= flash_class(key) %>">
                <%= value %>
           </div>
        <% end %>
  <% @user.errors.full_messages.each_with_index do |message| %>
        <%= message %><br>
      <%end%>
  <!--Displays Flash messages at the top of the page-->
   <% end %> 


  <div class="login">
  <div class="container">
    <div class="form">

    <h1>Sign up</h1>
<div style = "text-align:center">
    <!--Parameters for sign up form-->
      <%= f.text_field :first_name, :placeholder => "First name" %><br>
      <%= f.text_field :last_name, :placeholder => "Last name" %><br>
      <%= f.email_field :email, :placeholder => "Email" %><br>
      <%= f.password_field :password, :placeholder => "Password" %><br>
      <%= f.password_field :password_confirmation, :placeholder => "Confirm Password" %><br>
       <!--Submit form-->
       <input type="submit" class="buttoncolor" style="margin-right:-12px"><%= link_to '', new_user_path, data: {modal: true} %></input>      
    
</div>
  
    </div>
  </div>
</div>

<% end %> 
      
       
    
       